#!/bin/sh

set -e

cd "$(dirname "$0")/.."

npm install

# test if intents directory exists

if [ ! -d "intents" ]; then
  git clone --depth 1 https://github.com/home-assistant/intents.git
fi

cd intents
git pull
cd ..

